#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_ROOT="$(mktemp -d)"
trap 'rm -rf "${TEST_ROOT}"' EXIT

export HOME="${TEST_ROOT}/home"
export CODEX_HOME="${HOME}/.codex"
STUB_BIN="${TEST_ROOT}/bin"
mkdir -p "${CODEX_HOME}" "${HOME}/.agents/skills" "${STUB_BIN}"

cat > "${STUB_BIN}/codex" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF

cat > "${STUB_BIN}/bd" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = metrics ]; then
  exit 0
fi
if [ "${1:-}" = setup ] && [ "${2:-}" = codex ] && [ "${3:-}" = --global ]; then
  mkdir -p "${CODEX_HOME}"
  cat > "${CODEX_HOME}/hooks.json" <<'JSON'
{"hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"bd codex-hook SessionStart"}]}]}}
JSON
  cat > "${CODEX_HOME}/AGENTS.md" <<'RULES'
<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->
generated
RULES
  : > "${CODEX_HOME}/config.toml"
  exit 0
fi
exit 1
EOF

chmod +x "${STUB_BIN}/codex" "${STUB_BIN}/bd"
export PATH="${STUB_BIN}:${PATH}"

bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null

expected_session_command="${REPO_ROOT}/scripts/beads-codex-hook.sh SessionStart"
actual_session_command="$(jq -r '.hooks.SessionStart[0].hooks[0].command' "${CODEX_HOME}/hooks.json")"
[ "${actual_session_command}" = "${expected_session_command}" ] || {
  printf 'SessionStart hook mismatch: expected=[%s] actual=[%s]\n' "${expected_session_command}" "${actual_session_command}" >&2
  exit 1
}

stop_count="$(jq --arg command "${REPO_ROOT}/scripts/beads-stop-nudge.sh" '[.hooks.Stop[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${stop_count}" = 1 ] || {
  printf 'Stop hook count mismatch: expected=[1] actual=[%s]\n' "${stop_count}" >&2
  exit 1
}

bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null

session_count="$(jq --arg command "${expected_session_command}" '[.hooks.SessionStart[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${session_count}" = 1 ] || {
  printf 'SessionStart hook is not idempotent: expected=[1] actual=[%s]\n' "${session_count}" >&2
  exit 1
}

stop_count="$(jq --arg command "${REPO_ROOT}/scripts/beads-stop-nudge.sh" '[.hooks.Stop[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${stop_count}" = 1 ] || {
  printf 'Stop hook is not idempotent: expected=[1] actual=[%s]\n' "${stop_count}" >&2
  exit 1
}

printf 'PASS: macOS setup configures wrapper and Stop hooks idempotently\n'
