#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_ROOT="$(mktemp -d)"
trap 'rm -rf "${TEST_ROOT}"' EXIT

export HOME="${TEST_ROOT}/home"
export CODEX_HOME="${HOME}/.codex"
STUB_BIN="${TEST_ROOT}/bin"
mkdir -p "${CODEX_HOME}" "${HOME}/.agents/skills" "${STUB_BIN}"

cat > "${STUB_BIN}/codex" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF

cat > "${STUB_BIN}/bd" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = metrics ]; then
  exit 0
fi
if [ "${1:-}" = setup ] && [ "${2:-}" = codex ] && [ "${3:-}" = --global ]; then
  mkdir -p "${CODEX_HOME}"
  cat > "${CODEX_HOME}/hooks.json" <<'JSON'
{"hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"bd codex-hook SessionStart"}]}]}}
JSON
  cat > "${CODEX_HOME}/AGENTS.md" <<'RULES'
<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->
generated
RULES
  : > "${CODEX_HOME}/config.toml"
  exit 0
fi
exit 1
EOF

chmod +x "${STUB_BIN}/codex" "${STUB_BIN}/bd"
export PATH="${STUB_BIN}:${PATH}"

bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null

expected_session_command="${REPO_ROOT}/scripts/beads-codex-hook.sh SessionStart"
actual_session_command="$(jq -r '.hooks.SessionStart[0].hooks[0].command' "${CODEX_HOME}/hooks.json")"
[ "${actual_session_command}" = "${expected_session_command}" ] || {
  printf 'SessionStart hook mismatch: expected=[%s] actual=[%s]\n' "${expected_session_command}" "${actual_session_command}" >&2
  exit 1
}

stop_count="$(jq --arg command "${REPO_ROOT}/scripts/beads-stop-nudge.sh" '[.hooks.Stop[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${stop_count}" = 1 ] || {
  printf 'Stop hook count mismatch: expected=[1] actual=[%s]\n' "${stop_count}" >&2
  exit 1
}

bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null

session_count="$(jq --arg command "${expected_session_command}" '[.hooks.SessionStart[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${session_count}" = 1 ] || {
  printf 'SessionStart hook is not idempotent: expected=[1] actual=[%s]\n' "${session_count}" >&2
  exit 1
}

stop_count="$(jq --arg command "${REPO_ROOT}/scripts/beads-stop-nudge.sh" '[.hooks.Stop[]?.hooks[]? | select(.command == $command)] | length' "${CODEX_HOME}/hooks.json")"
[ "${stop_count}" = 1 ] || {
  printf 'Stop hook is not idempotent: expected=[1] actual=[%s]\n' "${stop_count}" >&2
  exit 1
}

printf 'PASS: macOS setup configures wrapper and Stop hooks idempotently\n'

local_rules="${CODEX_HOME}/AGENTS.local.md"
printf '# AGENTS.local.md\n\nPC固有のルール\n' > "${local_rules}"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
grep -Fq 'PC固有のルール' "${CODEX_HOME}/AGENTS.md"
[ ! -L "${CODEX_HOME}/AGENTS.md" ]

printf '# AGENTS.local.md\n\n更新したPC固有のルール\n' > "${local_rules}"
cp "${local_rules}" "${TEST_ROOT}/local-original.md"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
grep -Fq '更新したPC固有のルール' "${CODEX_HOME}/AGENTS.md"
cp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/combined.md"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
cmp "${local_rules}" "${TEST_ROOT}/local-original.md"
cmp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/combined.md"

rm "${local_rules}"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
[ -L "${CODEX_HOME}/AGENTS.md" ]
cmp "${REPO_ROOT}/rules/AGENTS.md" "${CODEX_HOME}/AGENTS.md"
printf 'PASS: local rules can be added, updated and removed through standard setup\n'

printf '\357\273\277# AGENTS.local.md\r\n\r\n改行形式の異なるルール' > "${local_rules}"
cp "${local_rules}" "${TEST_ROOT}/local-original.md"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
IFS= read -r marker < "${CODEX_HOME}/AGENTS.md"
[ "${marker}" = '<!-- generated by my-codex-rules -->' ]
if grep -Fq '# AGENTS.local.md' "${CODEX_HOME}/AGENTS.md" || grep -q "$(printf '\r')" "${CODEX_HOME}/AGENTS.md"; then
  echo 'Local heading or CRLF was not normalized' >&2
  exit 1
fi
grep -Fxq '改行形式の異なるルール' "${CODEX_HOME}/AGENTS.md"
cmp "${local_rules}" "${TEST_ROOT}/local-original.md"
printf 'PASS: generated local rules normalize BOM, CRLF and missing final newline\n'

cp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/combined.md"
printf 'override\n' > "${CODEX_HOME}/AGENTS.override.md"
if bash "${REPO_ROOT}/scripts/setup-beads.sh" > "${TEST_ROOT}/rejected.log" 2>&1; then
  echo 'Nonempty override should block setup' >&2
  exit 1
fi
cmp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/combined.md"
rm "${CODEX_HOME}/AGENTS.override.md"

sed '1s|my-codex-rules -->|my-codex-rules/scripts/setup-local-rules.sh -->|' "${TEST_ROOT}/combined.md" > "${CODEX_HOME}/AGENTS.md"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
cmp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/combined.md"

printf '利用者が直接管理しているルール\n' > "${CODEX_HOME}/AGENTS.md"
cp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/unmanaged.md"
if bash "${REPO_ROOT}/scripts/setup-beads.sh" > "${TEST_ROOT}/rejected.log" 2>&1; then
  echo 'Unmanaged rules should block setup' >&2
  exit 1
fi
cmp "${CODEX_HOME}/AGENTS.md" "${TEST_ROOT}/unmanaged.md"
cmp "${local_rules}" "${TEST_ROOT}/local-original.md"
cp "${TEST_ROOT}/combined.md" "${CODEX_HOME}/AGENTS.md"

: > "${local_rules}"
bash "${REPO_ROOT}/scripts/setup-beads.sh" >/dev/null
[ -L "${CODEX_HOME}/AGENTS.md" ]
cmp "${REPO_ROOT}/rules/AGENTS.md" "${CODEX_HOME}/AGENTS.md"
printf 'PASS: empty local rules, existing generated files and setup rejection preserve expected state\n'
