#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEX_DIR="${CODEX_HOME:-${HOME}/.codex}"
SKILLS_DIR="${HOME}/.agents/skills"
AGENTS_DST="${CODEX_DIR}/AGENTS.md"
LOCAL_AGENTS="${CODEX_DIR}/AGENTS.local.md"
LOCAL_AGENTS_MARKER='<!-- generated by my-codex-rules/scripts/setup-local-rules.sh -->'
HOOKS="${CODEX_DIR}/hooks.json"
CONFIG="${CODEX_DIR}/config.toml"
BACKUP_DIR="${CODEX_DIR}/my-codex-rules-beads/backup"
SESSION_START_COMMAND="${REPO_ROOT}/scripts/beads-codex-hook.sh SessionStart"

for command_name in codex bd jq; do
  command -v "${command_name}" >/dev/null 2>&1 || {
    echo "[fail] 依存コマンドが見つかりません: ${command_name}" >&2
    exit 1
  }
done

if [ -s "${CODEX_DIR}/AGENTS.override.md" ]; then
  echo "[fail] 非空の AGENTS.override.md が AGENTS.md を隠すため変更しません" >&2
  exit 1
fi
if [ -e "${AGENTS_DST}" ] && [ ! -L "${AGENTS_DST}" ] && ! cmp -s "${REPO_ROOT}/rules/AGENTS.md" "${AGENTS_DST}"; then
  if [ ! -s "${LOCAL_AGENTS}" ] || ! grep -Fqx "${LOCAL_AGENTS_MARKER}" "${AGENTS_DST}"; then
    echo "[fail] 既存の AGENTS.md が原本と異なるため変更しません: ${AGENTS_DST}" >&2
    exit 1
  fi
fi
for skill_name in project-bootstrap japanese-technical-writing; do
  skill_dst="${SKILLS_DIR}/${skill_name}"
  if [ -e "${skill_dst}" ] && [ ! -L "${skill_dst}" ]; then
    echo "[fail] 既存スキルが実体ディレクトリのため変更しません: ${skill_dst}" >&2
    exit 1
  fi
done

mkdir -p "${CODEX_DIR}" "${SKILLS_DIR}" "${BACKUP_DIR}"
for managed_name in AGENTS.md hooks.json config.toml; do
  managed_path="${CODEX_DIR}/${managed_name}"
  backup_path="${BACKUP_DIR}/${managed_name}.pre-setup"
  if [ -e "${managed_path}" ] && [ ! -e "${backup_path}" ]; then
    cp -p "${managed_path}" "${backup_path}"
  fi
done

bd metrics off >/dev/null 2>&1 || true
if [ ! -f "${HOOKS}" ] || ! jq -e --arg wrapper "${SESSION_START_COMMAND}" '
  [.hooks.SessionStart[]?.hooks[]?.command]
  | any(. == "bd codex-hook SessionStart" or . == $wrapper)
' "${HOOKS}" >/dev/null 2>&1; then
  bd setup codex --global
fi

if [ -f "${AGENTS_DST}" ] && grep -q 'BEGIN BEADS CODEX SETUP: generated by bd setup codex' "${AGENTS_DST}"; then
  rm "${AGENTS_DST}"
fi

link_path() {
  src="$1"
  dst="$2"
  if [ -L "${dst}" ] && [ "$(readlink "${dst}")" = "${src}" ]; then
    echo "[skip] シンボリックリンク設定済み: ${dst}"
  else
    ln -sfn "${src}" "${dst}"
    echo "[run ] シンボリックリンクを作成: ${dst}"
  fi
}

if [ -s "${LOCAL_AGENTS}" ]; then
  bash "${REPO_ROOT}/scripts/setup-local-rules.sh"
else
  link_path "${REPO_ROOT}/rules/AGENTS.md" "${AGENTS_DST}"
fi
link_path "${REPO_ROOT}/skills/project-bootstrap" "${SKILLS_DIR}/project-bootstrap"
link_path "${REPO_ROOT}/skills/japanese-technical-writing" "${SKILLS_DIR}/japanese-technical-writing"

tmp_hooks="$(mktemp)"
trap 'rm -f "${tmp_hooks:-}" "${tmp_config:-}"' EXIT
jq --arg command "${REPO_ROOT}/scripts/beads-stop-nudge.sh" --arg session_start "${SESSION_START_COMMAND}" '
  .hooks //= {}
  | .hooks.SessionStart = [(.hooks.SessionStart // [])[]
      | .hooks = [.hooks[]?
          | if (.command // "") == "bd codex-hook SessionStart"
            then .command = $session_start
            else .
            end
        ]
      | select((.hooks | length) > 0)
    ]
  | .hooks.Stop = (
      [(.hooks.Stop // [])[]
        | .hooks = [.hooks[]? | select((.command // "") | endswith("beads-stop-nudge.sh") | not)]
        | select((.hooks | length) > 0)
      ] + [{hooks:[{type:"command", command:$command, timeout:30, statusMessage:"Checking Beads progress"}]}]
    )
' "${HOOKS}" > "${tmp_hooks}"
jq -e . "${tmp_hooks}" >/dev/null
mv "${tmp_hooks}" "${HOOKS}"

add_config_default() {
  key="$1"
  value="$2"
  if sed 's/#.*$//' "${CONFIG}" | sed -n '1,/^[[:space:]]*\[/p' | grep -Eq "^[[:space:]]*${key}[[:space:]]*="; then
    return
  fi
  tmp_config="$(mktemp)"
  awk -v entry="${key} = \"${value}\"" '
    !inserted && /^[[:space:]]*\[/ { print entry; print ""; inserted=1 }
    { print }
    END { if (!inserted) print entry }
  ' "${CONFIG}" > "${tmp_config}"
  mv "${tmp_config}" "${CONFIG}"
}
touch "${CONFIG}"
add_config_default approval_policy on-request
add_config_default approvals_reviewer auto_review

echo "完了。Codex で /hooks を開いてフックを信頼し、Codex を再起動してください。"
