#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEX_DIR="${CODEX_HOME:-${HOME}/.codex}"
COMMON_RULES="${REPO_ROOT}/rules/AGENTS.md"
LOCAL_RULES="${CODEX_DIR}/AGENTS.local.md"
OUTPUT="${CODEX_DIR}/AGENTS.md"
MARKER='<!-- generated by my-codex-rules/scripts/setup-local-rules.sh -->'

if [ ! -s "${LOCAL_RULES}" ]; then
  echo "[fail] ローカルルールがありません: ${LOCAL_RULES}" >&2
  exit 1
fi

if [ -s "${CODEX_DIR}/AGENTS.override.md" ]; then
  echo "[fail] 非空の AGENTS.override.md が AGENTS.md を隠すため変更しません" >&2
  exit 1
fi

if [ -e "${OUTPUT}" ] && [ ! -L "${OUTPUT}" ] && ! grep -Fqx "${MARKER}" "${OUTPUT}"; then
  echo "[fail] 管理対象と確認できない AGENTS.md は上書きしません: ${OUTPUT}" >&2
  exit 1
fi

mkdir -p "${CODEX_DIR}"
tmp_output="$(mktemp "${CODEX_DIR}/AGENTS.md.XXXXXX")"
trap 'rm -f "${tmp_output:-}"' EXIT

{
  printf '%s\n\n' "${MARKER}"
  sed '1{/^# AGENTS\.md$/d;}' "${COMMON_RULES}"
  printf '\n\n'
  sed '1{/^# AGENTS\.local\.md$/d;}' "${LOCAL_RULES}"
} > "${tmp_output}"

mv "${tmp_output}" "${OUTPUT}"
echo "完了: ${OUTPUT}"
